# Generated by Django 3.2.4 on 2021-08-04 10:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enigmes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enigme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de modification')),
                ('theme', models.CharField(choices=[('NC', 'Non défini'), ('INT', 'Internet'), ('WEB', 'Le Web'), ('RS', 'Les réseaux sociaux'), ('DATA', 'Les données structurées et leur traitement'), ('LCM', 'Localisation, cartographie, mobilité'), ('IEOC', 'Informatique embarquée et objets connectés'), ('IMG', 'La photographie numérique'), ('PY', 'Python')], default='NC', max_length=4, verbose_name='thème')),
                ('enonce', models.TextField(verbose_name='énoncé')),
                ('reponse', models.CharField(max_length=100, verbose_name='réponse')),
                ('indication', models.TextField(blank=True, null=True, verbose_name='indication')),
                ('image', models.ImageField(blank=True, upload_to=enigmes.models.Enigme.repertoire_auteur, verbose_name="Image d'illustration")),
                ('fichier', models.FileField(blank=True, upload_to=enigmes.models.Enigme.repertoire_auteur, verbose_name='Fichier en pièce jointe')),
            ],
            options={
                'verbose_name': 'énigme',
            },
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('correction', models.BooleanField(default=False, verbose_name='correction')),
                ('ordre_aleatoire', models.BooleanField(default=False, verbose_name='ordre aléatoire des énigmes')),
                ('cle', models.CharField(blank=True, default='', max_length=200, verbose_name='clé')),
                ('code', models.CharField(default=enigmes.models.generer_code_enquete_unique, max_length=10, null=True, unique=True, verbose_name="code de l'enquête")),
            ],
            options={
                'verbose_name': 'enquête',
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponses', models.TextField(blank=True, null=True, verbose_name='réponses')),
                ('id_eleve', models.CharField(default='', max_length=100, verbose_name='id_eleve')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('enquete', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquete', to='enigmes.enquete')),
            ],
            options={
                'verbose_name': 'résultat',
            },
        ),
    ]
