# Generated by Django 3.2.4 on 2021-10-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigme',
            name='fichier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pj', to='enigmes.fichier'),
        ),
    ]
