# Generated by Django 3.2.4 on 2021-08-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='indications',
            field=models.BooleanField(default=True, verbose_name='indications'),
        ),
    ]
