# Generated by Django 3.2.4 on 2021-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0003_enquete_indications'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='score',
            field=models.BooleanField(default=True, verbose_name='score'),
        ),
    ]
