# Generated by Django 3.2.4 on 2021-11-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0003_auto_20211023_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(max_length=100, verbose_name='réponse')),
                ('enigme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enigme', to='enigmes.enigme')),
            ],
        ),
    ]
