# Generated by Django 3.2.4 on 2021-08-12 17:20

from django.db import migrations, models
import enigmes.models
import enigmes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0004_enquete_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigme',
            name='fichier',
            field=models.FileField(blank=True, upload_to=enigmes.models.Enigme.repertoire_auteur, validators=[enigmes.validators.FileValidator(content_types=('text/csv', 'application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'text/x-python', 'text/html', 'text/css', 'application/json', 'image/jpeg', 'image/png'), max_size=1024000)], verbose_name='Fichier en pièce jointe'),
        ),
        migrations.AlterField(
            model_name='enigme',
            name='image',
            field=models.ImageField(blank=True, upload_to=enigmes.models.Enigme.repertoire_auteur, validators=[enigmes.validators.FileValidator(content_types=('image/jpeg', 'image/png'), max_size=307200)], verbose_name="Image d'illustration"),
        ),
    ]
