# Generated by Django 3.2.4 on 2021-11-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0004_reponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enigme',
            name='reponse',
        ),
        migrations.AlterField(
            model_name='reponse',
            name='enigme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponse', to='enigmes.enigme'),
        ),
    ]
