# Generated by Django 3.2.4 on 2021-11-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0005_auto_20211113_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigme',
            name='reponse',
            field=models.CharField(default='essai', max_length=100, verbose_name='réponse'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
    ]
