# Generated by Django 3.2.4 on 2021-11-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0006_auto_20211117_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigme',
            name='reponse2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='réponse 2'),
        ),
        migrations.AddField(
            model_name='enigme',
            name='reponse3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='réponse 3'),
        ),
        migrations.AddField(
            model_name='enigme',
            name='reponse4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='réponse 4'),
        ),
    ]
