# Generated by Django 3.2.4 on 2021-09-02 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0007_auto_20210817_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigme',
            name='credits_image',
            field=models.TextField(blank=True, null=True, verbose_name='crédits'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='id_eleve',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator('^([a-zA-Z]?)[0-9\\-\\_]*', "L'identifiant saisi n'est pas valide. Veuillez consultez votre professeur.")], verbose_name='id_eleve'),
        ),
    ]
