# Generated by Django 3.2.4 on 2021-12-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0008_auto_20211211_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enigme',
            old_name='reponse_libre',
            new_name='question_libre',
        ),
    ]
