# Generated by Django 3.2.4 on 2021-09-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0009_alter_enigme_credits_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigme',
            name='url_image',
            field=models.URLField(blank=True, null=True, verbose_name="URL de l'image"),
        ),
    ]
