# Generated by Django 3.2.4 on 2021-12-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0009_rename_reponse_libre_enigme_question_libre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigme',
            name='question_libre',
            field=models.BooleanField(default=False, verbose_name='Réponse libre attendue'),
        ),
        migrations.AlterField(
            model_name='enigme',
            name='reponse',
            field=models.CharField(max_length=300, verbose_name='réponse'),
        ),
        migrations.AlterField(
            model_name='enigme',
            name='reponse2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='réponse 2'),
        ),
        migrations.AlterField(
            model_name='enigme',
            name='reponse3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='réponse 3'),
        ),
        migrations.AlterField(
            model_name='enigme',
            name='reponse4',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='réponse 4'),
        ),
    ]
