# Generated by Django 3.2.4 on 2021-12-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0010_auto_20211211_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigme',
            name='reponse_libre',
            field=models.TextField(blank=True, null=True, verbose_name='réponse libre'),
        ),
        migrations.AlterField(
            model_name='enigme',
            name='reponse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='réponse'),
        ),
        migrations.AlterField(
            model_name='enigme',
            name='reponse2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='réponse 2'),
        ),
        migrations.AlterField(
            model_name='enigme',
            name='reponse3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='réponse 3'),
        ),
        migrations.AlterField(
            model_name='enigme',
            name='reponse4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='réponse 4'),
        ),
    ]
