# Generated by Django 3.2.4 on 2022-01-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigmes', '0011_auto_20211211_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigme',
            name='commentaires',
            field=models.TextField(blank=True, null=True, verbose_name='commentaires'),
        ),
    ]
