# Generated by Django 3.2.4 on 2021-08-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un compte existe déjà pour cette adresse email.'}, max_length=60, unique=True, verbose_name='email'),
        ),
    ]
